[package]
name = "cdumay_result"
version = "0.3.0"

authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
categories = ["caching", "data-structures", "encoding"]
description = """A library to serialize and deserialize result using serde"""
documentation = "https://docs.rs/cdumay_result"
edition = "2021"
homepage = "https://github.com/cdumay/rust-cdumay_result"
keywords = ["Error", "serde", "Result"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/cdumay/rust-cdumay_result"

[badges]
gitlab = { repository = "cdumay/rust-cdumay_result" }
travis-ci = { repository = "cdumay/rust-cdumay_result" }
maintenance = { status = "as-is" }

[dependencies]
cdumay_core = { git = "https://github.com/cdumay/rust-cdumay_core" }
cdumay_error = { git = "https://github.com/cdumay/rust-cdumay_error" }
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.117"
